name: Java CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11
        cache: maven

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Run tests
      run: mvn verify --file pom.xml

    - name: Publish to GitHub Packages
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: mvn deploy --file pom.xml

    - uses: actions/setup-java@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        distribution: zulu
        java-version: 11
        server-id: nexus
        server-username: NEXUS_USERNAME
        server-password: NEXUS_PASSWORD

    - name: Publish to Nexus
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        NEXUS_URL: ${{ secrets.NEXUS_URL }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: mvn deploy -DaltDeploymentRepository="nexus::${NEXUS_URL}/repository/releases"
