name: Java CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11
        cache: maven

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Run tests
      run: mvn verify --file pom.xml
